package com.jianfei.core.mapper;

import com.jianfei.core.bean.AppAirportArchive;

public interface AppAirportArchiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ariport_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int deleteByPrimaryKey(Integer archiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ariport_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int insert(AppAirportArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ariport_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int insertSelective(AppAirportArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ariport_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    AppAirportArchive selectByPrimaryKey(Integer archiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ariport_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int updateByPrimaryKeySelective(AppAirportArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_ariport_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int updateByPrimaryKey(AppAirportArchive record);
}