package com.jianfei.core.mapper;

import com.jianfei.core.bean.AppAirportTrans;
import com.jianfei.core.common.persistence.MyBatisDao;

@MyBatisDao
public interface AppAirportTransMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_airport_trans
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_airport_trans
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    int insert(AppAirportTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_airport_trans
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    int insertSelective(AppAirportTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_airport_trans
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    AppAirportTrans selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_airport_trans
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    int updateByPrimaryKeySelective(AppAirportTrans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_airport_trans
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    int updateByPrimaryKey(AppAirportTrans record);
}