package com.jianfei.core.mapper;

import java.util.List;
import java.util.Map;

import com.jianfei.core.bean.AppAirportTrans;
import com.jianfei.core.common.persistence.MyBatisDao;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface AppAirportTransMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_airport_trans
	 *
	 * @mbggenerated Tue Jul 05 17:33:20 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_airport_trans
	 *
	 * @mbggenerated Tue Jul 05 17:33:20 CST 2016
	 */
	int insert(AppAirportTrans record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_airport_trans
	 *
	 * @mbggenerated Tue Jul 05 17:33:20 CST 2016
	 */
	int insertSelective(AppAirportTrans record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_airport_trans
	 *
	 * @mbggenerated Tue Jul 05 17:33:20 CST 2016
	 */
	AppAirportTrans selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_airport_trans
	 *
	 * @mbggenerated Tue Jul 05 17:33:20 CST 2016
	 */
	int updateByPrimaryKeySelective(AppAirportTrans record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_airport_trans
	 *
	 * @mbggenerated Tue Jul 05 17:33:20 CST 2016
	 */
	int updateByPrimaryKey(AppAirportTrans record);

	/**
	 * mapList(根据条件查询接送机信息)
	 * 
	 * @param searchParams
	 * @return List<Map<String, Object>>
	 * @version 1.0.0
	 */
	List<Map<String, Object>> mapList(Map<String, Object> searchParams);

	/**
	 * updateState(更改接送机状态)
	 * 
	 * @param params
	 *            void
	 * @version 1.0.0
	 */
	void updateState(Map<String, Object> params);

	/**
	 * pickupLook(查看接送机详情)
	 * 
	 * @param id
	 *            接送机主键
	 * @version 1.0.0
	 */
	List<Map<String, Object>> pickupLook(String id);

	/**
	 * 根据手机号查询用户预定机记录
	 * @param phone
	 * @return
     */
	List<AppAirportTrans> selectByPhone(@Param(value = "phone")String phone, @Param(value = "cardNo")String cardNo);
}