package com.jianfei.core.mapper;

import com.jianfei.core.bean.AppConfig;

public interface AppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int insertSelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    AppConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int updateByPrimaryKeySelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int updateByPrimaryKey(AppConfig record);
}