package com.jianfei.core.mapper;

import java.util.List;
import java.util.Map;

import com.jianfei.core.bean.AppCustomer;
import com.jianfei.core.common.persistence.MyBatisDao;

@MyBatisDao
public interface AppCustomerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_customer
	 *
	 * @mbggenerated Fri May 27 14:50:45 CST 2016
	 */
	int insert(AppCustomer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_customer
	 *
	 * @mbggenerated Fri May 27 14:50:45 CST 2016
	 */
	int insertSelective(AppCustomer record);

	int deleteByPrimaryKey(String customerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table app_customer
	 *
	 * @mbggenerated Thu Jun 02 16:39:31 CST 2016
	 */
	int updateByPrimaryKeySelective(AppCustomer record);

	AppCustomer selectByPrimaryKey(String customerId);

	List<AppCustomer> selectCustomerDetailByPhone(String phone);

	List<AppCustomer> selectByPhone(String phone);

	List<Map<String, Object>> get(Map<String, Object> map);

	/**
	 * updateDeliveryState(更新投递状态为已投递)
	 * 
	 * @param id
	 *            VIP用户 主键Id void
	 * @version 1.0.0
	 */
	void updateDeliveryState(String id);
}