package com.jianfei.core.mapper;

import com.jianfei.core.bean.AppConfig;
import com.jianfei.core.common.persistence.MyBatisDao;
import com.jianfei.core.dto.VipCardInfoDto;

import java.util.List;
import java.util.Map;

@MyBatisDao
public interface AppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Mon Jun 06 18:18:35 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Mon Jun 06 18:18:35 CST 2016
     */
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Mon Jun 06 18:18:35 CST 2016
     */
    int insertSelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Mon Jun 06 18:18:35 CST 2016
     */
    AppConfig selectByPrimaryKey(String id);

    //更新权益信息
    int updateByPrimaryKeySelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Mon Jun 06 18:18:35 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Mon Jun 06 18:18:35 CST 2016
     */
    int updateByPrimaryKey(AppConfig record);

    VipCardInfoDto selectVipCardInfo(int type);

    List<AppConfig> selectByType(int type);
    
    //分页展示权益信息
    List<AppConfig> page(Map<String,Object> map);
    
    //逻辑删除权益
    int delRight(String id);
}