/**
 * @项目名:vip
 * @版本信息:1.0
 * @date:2016年5月20日-下午2:52:10
 * Copyright (c) 2016建飞科联公司-版权所有
 *
 */
package com.jianfei.core.mapper;

import com.jianfei.core.bean.AppOrderCard;
import com.jianfei.core.common.persistence.MyBatisDao;
import com.jianfei.core.dto.VipCardUseDetailInfo;
import org.apache.ibatis.annotations.Param;

/**
 *
 * @Description: TODO
 * @author: guo.jian@jianfeitech.com 
 * @date: 2016年5月20日 下午2:52:10 
 * 
 * @version 1.0.0
 *
 */
@MyBatisDao
public interface AppOrderCardMapper {
	//返回vip卡号和初始金额
	AppOrderCard getAppOrderCard(String orderId);

	/**
	 * 根据用户手机号获取订单及VIP卡相关信息
	 * @param customerPhone
	 * @return
     */
	VipCardUseDetailInfo getVipCardUseDetailInfo(@Param("customerPhone") String customerPhone );

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_order_card
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_order_card
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	int insert(AppOrderCard record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_order_card
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	int insertSelective(AppOrderCard record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_order_card
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	AppOrderCard selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_order_card
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	int updateByPrimaryKeySelective(AppOrderCard record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table app_order_card
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	int updateByPrimaryKey(AppOrderCard record);
}
