package com.jianfei.core.mapper;

import com.jianfei.core.bean.AppOrderArchive;

public interface AppOrderArchiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_order_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_order_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int insert(AppOrderArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_order_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int insertSelective(AppOrderArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_order_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    AppOrderArchive selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_order_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int updateByPrimaryKeySelective(AppOrderArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_order_archive
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    int updateByPrimaryKey(AppOrderArchive record);
}