package com.jianfei.core.mapper;

import com.jianfei.core.bean.AppVersion;
import com.jianfei.core.common.persistence.MyBatisDao;

import java.util.List;
@MyBatisDao
public interface AppVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    int insert(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    int insertSelective(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    AppVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    int updateByPrimaryKeySelective(AppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    int updateByPrimaryKey(AppVersion record);

    /**
     * 根据版本号获取列表
     * @param channel
     * @return
     */
    List<AppVersion> getVersions(String channel);
}