package com.jianfei.core.mapper;

import com.jianfei.core.bean.YdycAirports;
import com.jianfei.core.common.persistence.MyBatisDao;
import com.jianfei.core.dto.BaseDto;

import java.util.List;

@MyBatisDao
public interface YdycAirportsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ydyc_airports
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ydyc_airports
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    int insert(YdycAirports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ydyc_airports
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    int insertSelective(YdycAirports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ydyc_airports
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    YdycAirports selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ydyc_airports
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    int updateByPrimaryKeySelective(YdycAirports record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ydyc_airports
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    int updateByPrimaryKey(YdycAirports record);

    /**
     * 获取支持的城市列表
     * @return
     */
    List<BaseDto> getCityList();

    /**
     * 根据城市获取相关列表
     * @param record
     * @return
     */
    List<YdycAirports> selectAirports(YdycAirports record);
}