package com.jianfei.core.bean;

import java.util.Date;

public class AppAirportTrans {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.phone
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.name
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.airport_id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String airportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.airport_name
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String airportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.flight_lou
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String flightLou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.flight_num
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String flightNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.flight_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Date flightDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.number_peers
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Integer numberPeers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.gooff_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Date gooffDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.pid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.pname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.sid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.sname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.cid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.cname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.detail_address
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.create_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.pickup_type
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Integer pickupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.remark
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.submit
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Integer submit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.deal_id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Integer dealId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_airport_trans.update_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.id
     *
     * @return the value of app_airport_trans.id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.id
     *
     * @param id the value for app_airport_trans.id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.phone
     *
     * @return the value of app_airport_trans.phone
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.phone
     *
     * @param phone the value for app_airport_trans.phone
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.name
     *
     * @return the value of app_airport_trans.name
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.name
     *
     * @param name the value for app_airport_trans.name
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.airport_id
     *
     * @return the value of app_airport_trans.airport_id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.airport_id
     *
     * @param airportId the value for app_airport_trans.airport_id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setAirportId(String airportId) {
        this.airportId = airportId == null ? null : airportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.airport_name
     *
     * @return the value of app_airport_trans.airport_name
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getAirportName() {
        return airportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.airport_name
     *
     * @param airportName the value for app_airport_trans.airport_name
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setAirportName(String airportName) {
        this.airportName = airportName == null ? null : airportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.flight_lou
     *
     * @return the value of app_airport_trans.flight_lou
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getFlightLou() {
        return flightLou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.flight_lou
     *
     * @param flightLou the value for app_airport_trans.flight_lou
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setFlightLou(String flightLou) {
        this.flightLou = flightLou == null ? null : flightLou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.flight_num
     *
     * @return the value of app_airport_trans.flight_num
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getFlightNum() {
        return flightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.flight_num
     *
     * @param flightNum the value for app_airport_trans.flight_num
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setFlightNum(String flightNum) {
        this.flightNum = flightNum == null ? null : flightNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.flight_date
     *
     * @return the value of app_airport_trans.flight_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Date getFlightDate() {
        return flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.flight_date
     *
     * @param flightDate the value for app_airport_trans.flight_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setFlightDate(Date flightDate) {
        this.flightDate = flightDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.number_peers
     *
     * @return the value of app_airport_trans.number_peers
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Integer getNumberPeers() {
        return numberPeers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.number_peers
     *
     * @param numberPeers the value for app_airport_trans.number_peers
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setNumberPeers(Integer numberPeers) {
        this.numberPeers = numberPeers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.gooff_date
     *
     * @return the value of app_airport_trans.gooff_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Date getGooffDate() {
        return gooffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.gooff_date
     *
     * @param gooffDate the value for app_airport_trans.gooff_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setGooffDate(Date gooffDate) {
        this.gooffDate = gooffDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.pid
     *
     * @return the value of app_airport_trans.pid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.pid
     *
     * @param pid the value for app_airport_trans.pid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.pname
     *
     * @return the value of app_airport_trans.pname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.pname
     *
     * @param pname the value for app_airport_trans.pname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.sid
     *
     * @return the value of app_airport_trans.sid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.sid
     *
     * @param sid the value for app_airport_trans.sid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.sname
     *
     * @return the value of app_airport_trans.sname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.sname
     *
     * @param sname the value for app_airport_trans.sname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.cid
     *
     * @return the value of app_airport_trans.cid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.cid
     *
     * @param cid the value for app_airport_trans.cid
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.cname
     *
     * @return the value of app_airport_trans.cname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.cname
     *
     * @param cname the value for app_airport_trans.cname
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.detail_address
     *
     * @return the value of app_airport_trans.detail_address
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.detail_address
     *
     * @param detailAddress the value for app_airport_trans.detail_address
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.create_date
     *
     * @return the value of app_airport_trans.create_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.create_date
     *
     * @param createDate the value for app_airport_trans.create_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.pickup_type
     *
     * @return the value of app_airport_trans.pickup_type
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Integer getPickupType() {
        return pickupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.pickup_type
     *
     * @param pickupType the value for app_airport_trans.pickup_type
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setPickupType(Integer pickupType) {
        this.pickupType = pickupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.remark
     *
     * @return the value of app_airport_trans.remark
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.remark
     *
     * @param remark the value for app_airport_trans.remark
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.submit
     *
     * @return the value of app_airport_trans.submit
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Integer getSubmit() {
        return submit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.submit
     *
     * @param submit the value for app_airport_trans.submit
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setSubmit(Integer submit) {
        this.submit = submit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.deal_id
     *
     * @return the value of app_airport_trans.deal_id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.deal_id
     *
     * @param dealId the value for app_airport_trans.deal_id
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_airport_trans.update_date
     *
     * @return the value of app_airport_trans.update_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_airport_trans.update_date
     *
     * @param updateDate the value for app_airport_trans.update_date
     *
     * @mbggenerated Tue Jul 05 17:33:20 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}