package com.jianfei.core.bean;

import java.util.Date;

public class AppAirportArchive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ariport_archive.archive_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private Integer archiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ariport_archive.card_num
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private Integer cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ariport_archive.archiive_time
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private Date archiiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_ariport_archive.airport_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private String airportId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ariport_archive.archive_id
     *
     * @return the value of app_ariport_archive.archive_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public Integer getArchiveId() {
        return archiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ariport_archive.archive_id
     *
     * @param archiveId the value for app_ariport_archive.archive_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setArchiveId(Integer archiveId) {
        this.archiveId = archiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ariport_archive.card_num
     *
     * @return the value of app_ariport_archive.card_num
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public Integer getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ariport_archive.card_num
     *
     * @param cardNum the value for app_ariport_archive.card_num
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setCardNum(Integer cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ariport_archive.archiive_time
     *
     * @return the value of app_ariport_archive.archiive_time
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public Date getArchiiveTime() {
        return archiiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ariport_archive.archiive_time
     *
     * @param archiiveTime the value for app_ariport_archive.archiive_time
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setArchiiveTime(Date archiiveTime) {
        this.archiiveTime = archiiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_ariport_archive.airport_id
     *
     * @return the value of app_ariport_archive.airport_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_ariport_archive.airport_id
     *
     * @param airportId the value for app_ariport_archive.airport_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setAirportId(String airportId) {
        this.airportId = airportId == null ? null : airportId.trim();
    }
}