package com.jianfei.core.bean;

public class AppConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_config.id
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_config.type
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_config.content
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_config.id
     *
     * @return the value of app_config.id
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_config.id
     *
     * @param id the value for app_config.id
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_config.type
     *
     * @return the value of app_config.type
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_config.type
     *
     * @param type the value for app_config.type
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_config.content
     *
     * @return the value of app_config.content
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_config.content
     *
     * @param content the value for app_config.content
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}