package com.jianfei.core.bean;

import java.util.Date;

public class AppInvoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.invoice_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String invoiceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.order_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.postcode
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private Integer postcode;

    /**
     * 发票类型 0 个人 1 公司
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.invoice_title
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String invoiceTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.consignee_name
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String consigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.consignee_phone
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String consigneePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.province
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.city
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.country
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.address
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.dtflag
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private Integer dtflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.invoice_no
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String invoiceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.province_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.city_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.country_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String countryId;

    /**
     * 发票种类 0 普通 1 增值税
     */
    private Integer invoiceKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.creater_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String createrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.updater_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.update_time
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.create_time
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.company_name
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.company_address
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.company_phone
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String companyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.business_license_url
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String businessLicenseUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.company_tax_no
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String companyTaxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.invoice_state
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private Integer invoiceState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_invoice.invoice_content
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    private String invoiceContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.invoice_id
     *
     * @return the value of app_invoice.invoice_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.invoice_id
     *
     * @param invoiceId the value for app_invoice.invoice_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId == null ? null : invoiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.order_id
     *
     * @return the value of app_invoice.order_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.order_id
     *
     * @param orderId the value for app_invoice.order_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.postcode
     *
     * @return the value of app_invoice.postcode
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public Integer getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.postcode
     *
     * @param postcode the value for app_invoice.postcode
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setPostcode(Integer postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.invoice_type
     *
     * @return the value of app_invoice.invoice_type
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.invoice_type
     *
     * @param invoiceType the value for app_invoice.invoice_type
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.invoice_title
     *
     * @return the value of app_invoice.invoice_title
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getInvoiceTitle() {
        return invoiceTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.invoice_title
     *
     * @param invoiceTitle the value for app_invoice.invoice_title
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setInvoiceTitle(String invoiceTitle) {
        this.invoiceTitle = invoiceTitle == null ? null : invoiceTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.consignee_name
     *
     * @return the value of app_invoice.consignee_name
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.consignee_name
     *
     * @param consigneeName the value for app_invoice.consignee_name
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName == null ? null : consigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.consignee_phone
     *
     * @return the value of app_invoice.consignee_phone
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.consignee_phone
     *
     * @param consigneePhone the value for app_invoice.consignee_phone
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.province
     *
     * @return the value of app_invoice.province
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.province
     *
     * @param province the value for app_invoice.province
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.city
     *
     * @return the value of app_invoice.city
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.city
     *
     * @param city the value for app_invoice.city
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.country
     *
     * @return the value of app_invoice.country
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.country
     *
     * @param country the value for app_invoice.country
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.address
     *
     * @return the value of app_invoice.address
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.address
     *
     * @param address the value for app_invoice.address
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.dtflag
     *
     * @return the value of app_invoice.dtflag
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public Integer getDtflag() {
        return dtflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.dtflag
     *
     * @param dtflag the value for app_invoice.dtflag
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setDtflag(Integer dtflag) {
        this.dtflag = dtflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.invoice_no
     *
     * @return the value of app_invoice.invoice_no
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.invoice_no
     *
     * @param invoiceNo the value for app_invoice.invoice_no
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.province_id
     *
     * @return the value of app_invoice.province_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.province_id
     *
     * @param provinceId the value for app_invoice.province_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.city_id
     *
     * @return the value of app_invoice.city_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.city_id
     *
     * @param cityId the value for app_invoice.city_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.country_id
     *
     * @return the value of app_invoice.country_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.country_id
     *
     * @param countryId the value for app_invoice.country_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.invoice_kind
     *
     * @return the value of app_invoice.invoice_kind
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public Integer getInvoiceKind() {
        return invoiceKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.invoice_kind
     *
     * @param invoiceKind the value for app_invoice.invoice_kind
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setInvoiceKind(Integer invoiceKind) {
        this.invoiceKind = invoiceKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.creater_id
     *
     * @return the value of app_invoice.creater_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.creater_id
     *
     * @param createrId the value for app_invoice.creater_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.updater_id
     *
     * @return the value of app_invoice.updater_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.updater_id
     *
     * @param updaterId the value for app_invoice.updater_id
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.update_time
     *
     * @return the value of app_invoice.update_time
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.update_time
     *
     * @param updateTime the value for app_invoice.update_time
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.create_time
     *
     * @return the value of app_invoice.create_time
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.create_time
     *
     * @param createTime the value for app_invoice.create_time
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.company_name
     *
     * @return the value of app_invoice.company_name
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.company_name
     *
     * @param companyName the value for app_invoice.company_name
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.company_address
     *
     * @return the value of app_invoice.company_address
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.company_address
     *
     * @param companyAddress the value for app_invoice.company_address
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.company_phone
     *
     * @return the value of app_invoice.company_phone
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.company_phone
     *
     * @param companyPhone the value for app_invoice.company_phone
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone == null ? null : companyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.business_license_url
     *
     * @return the value of app_invoice.business_license_url
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getBusinessLicenseUrl() {
        return businessLicenseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.business_license_url
     *
     * @param businessLicenseUrl the value for app_invoice.business_license_url
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setBusinessLicenseUrl(String businessLicenseUrl) {
        this.businessLicenseUrl = businessLicenseUrl == null ? null : businessLicenseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.company_tax_no
     *
     * @return the value of app_invoice.company_tax_no
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getCompanyTaxNo() {
        return companyTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.company_tax_no
     *
     * @param companyTaxNo the value for app_invoice.company_tax_no
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setCompanyTaxNo(String companyTaxNo) {
        this.companyTaxNo = companyTaxNo == null ? null : companyTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.invoice_state
     *
     * @return the value of app_invoice.invoice_state
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public Integer getInvoiceState() {
        return invoiceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.invoice_state
     *
     * @param invoiceState the value for app_invoice.invoice_state
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setInvoiceState(Integer invoiceState) {
        this.invoiceState = invoiceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_invoice.invoice_content
     *
     * @return the value of app_invoice.invoice_content
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public String getInvoiceContent() {
        return invoiceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_invoice.invoice_content
     *
     * @param invoiceContent the value for app_invoice.invoice_content
     *
     * @mbggenerated Tue Jul 05 14:19:02 CST 2016
     */
    public void setInvoiceContent(String invoiceContent) {
        this.invoiceContent = invoiceContent == null ? null : invoiceContent.trim();
    }
}