package com.jianfei.core.bean;

import java.util.Date;

public class AppOrderArchive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.file_id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.file_time
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private Date fileTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.order_num
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.dflag
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private Integer dflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.bname
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.airportname
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String airportname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.airport_id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String airportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.year
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.month
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.day
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.province
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.dayweek
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    private String dayweek;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.file_id
     *
     * @return the value of app_order_archive.file_id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.file_id
     *
     * @param fileId the value for app_order_archive.file_id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.id
     *
     * @return the value of app_order_archive.id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.id
     *
     * @param id the value for app_order_archive.id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.file_time
     *
     * @return the value of app_order_archive.file_time
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public Date getFileTime() {
        return fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.file_time
     *
     * @param fileTime the value for app_order_archive.file_time
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setFileTime(Date fileTime) {
        this.fileTime = fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.order_num
     *
     * @return the value of app_order_archive.order_num
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.order_num
     *
     * @param orderNum the value for app_order_archive.order_num
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.dflag
     *
     * @return the value of app_order_archive.dflag
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public Integer getDflag() {
        return dflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.dflag
     *
     * @param dflag the value for app_order_archive.dflag
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setDflag(Integer dflag) {
        this.dflag = dflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.bname
     *
     * @return the value of app_order_archive.bname
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.bname
     *
     * @param bname the value for app_order_archive.bname
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.airportname
     *
     * @return the value of app_order_archive.airportname
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getAirportname() {
        return airportname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.airportname
     *
     * @param airportname the value for app_order_archive.airportname
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setAirportname(String airportname) {
        this.airportname = airportname == null ? null : airportname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.airport_id
     *
     * @return the value of app_order_archive.airport_id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.airport_id
     *
     * @param airportId the value for app_order_archive.airport_id
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setAirportId(String airportId) {
        this.airportId = airportId == null ? null : airportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.year
     *
     * @return the value of app_order_archive.year
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.year
     *
     * @param year the value for app_order_archive.year
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.month
     *
     * @return the value of app_order_archive.month
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.month
     *
     * @param month the value for app_order_archive.month
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.day
     *
     * @return the value of app_order_archive.day
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.day
     *
     * @param day the value for app_order_archive.day
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.province
     *
     * @return the value of app_order_archive.province
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.province
     *
     * @param province the value for app_order_archive.province
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.dayweek
     *
     * @return the value of app_order_archive.dayweek
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public String getDayweek() {
        return dayweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.dayweek
     *
     * @param dayweek the value for app_order_archive.dayweek
     *
     * @mbggenerated Mon Jun 06 00:48:06 CST 2016
     */
    public void setDayweek(String dayweek) {
        this.dayweek = dayweek == null ? null : dayweek.trim();
    }
}