/**
 * @项目名:vip
 * @版本信息:1.0
 * @date:2016年5月20日-下午2:53:19
 * Copyright (c) 2016建飞科联公司-版权所有
 *
 */
package com.jianfei.core.bean;

/**
 * 订单vip卡表
 * @Description:
 * @author: guo.jian@jianfeitech.com 
 * @date: 2016年5月20日 下午2:53:19 
 * 
 * @version 1.0.0
 *
 */
public class AppOrderCard {
	private String cardNo;//vip卡号

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column app_order_card.id
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column app_order_card.order_id
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	private String orderId;


	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column app_order_card.card_num
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	private Integer cardNum;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column app_order_card.init_money
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	private Float initMoney;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column app_order_card.card_type
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	private Integer cardType;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column app_order_card.id
	 *
	 * @return the value of app_order_card.id
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column app_order_card.id
	 *
	 * @param id the value for app_order_card.id
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column app_order_card.order_id
	 *
	 * @return the value of app_order_card.order_id
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column app_order_card.order_id
	 *
	 * @param orderId the value for app_order_card.order_id
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}


	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column app_order_card.card_num
	 *
	 * @return the value of app_order_card.card_num
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public Integer getCardNum() {
		return cardNum;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column app_order_card.card_num
	 *
	 * @param cardNum the value for app_order_card.card_num
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public void setCardNum(Integer cardNum) {
		this.cardNum = cardNum;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column app_order_card.init_money
	 *
	 * @return the value of app_order_card.init_money
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public float getInitMoney() {
		return initMoney;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column app_order_card.init_money
	 *
	 * @param initMoney the value for app_order_card.init_money
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public void setInitMoney(Float initMoney) {
		this.initMoney = initMoney;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column app_order_card.card_type
	 *
	 * @return the value of app_order_card.card_type
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public Integer getCardType() {
		return cardType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column app_order_card.card_type
	 *
	 * @param cardType the value for app_order_card.card_type
	 *
	 * @mbggenerated Thu Jun 02 14:29:29 CST 2016
	 */
	public void setCardType(Integer cardType) {
		this.cardType = cardType;
	}

	public String getCardNo() {
		return cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}
}
