package com.jianfei.core.bean;

import java.util.Date;

public class AppOrderArchive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.file_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.file_time
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private Date fileTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.order_num
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.dflag
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private Integer dflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_order_archive.airport_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    private String airportId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.file_id
     *
     * @return the value of app_order_archive.file_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.file_id
     *
     * @param fileId the value for app_order_archive.file_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.id
     *
     * @return the value of app_order_archive.id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.id
     *
     * @param id the value for app_order_archive.id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.file_time
     *
     * @return the value of app_order_archive.file_time
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public Date getFileTime() {
        return fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.file_time
     *
     * @param fileTime the value for app_order_archive.file_time
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setFileTime(Date fileTime) {
        this.fileTime = fileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.order_num
     *
     * @return the value of app_order_archive.order_num
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.order_num
     *
     * @param orderNum the value for app_order_archive.order_num
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.dflag
     *
     * @return the value of app_order_archive.dflag
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public Integer getDflag() {
        return dflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.dflag
     *
     * @param dflag the value for app_order_archive.dflag
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setDflag(Integer dflag) {
        this.dflag = dflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_order_archive.airport_id
     *
     * @return the value of app_order_archive.airport_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_order_archive.airport_id
     *
     * @param airportId the value for app_order_archive.airport_id
     *
     * @mbggenerated Fri May 20 13:59:51 CST 2016
     */
    public void setAirportId(String airportId) {
        this.airportId = airportId == null ? null : airportId.trim();
    }
}