package com.jianfei.core.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;
import java.util.Date;

public class AppVersion implements Serializable {

    private static final long serialVersionUID = 7785258523421583464L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.id
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.channel
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.code
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.lowest_code
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    private String lowestCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.update_url
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    private String updateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.describe
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.create_time
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    @JsonIgnore
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.creater
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    @JsonIgnore
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_version.is_exist
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    @JsonIgnore
    private Integer isExist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.id
     *
     * @return the value of app_version.id
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.id
     *
     * @param id the value for app_version.id
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.channel
     *
     * @return the value of app_version.channel
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.channel
     *
     * @param channel the value for app_version.channel
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.code
     *
     * @return the value of app_version.code
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.code
     *
     * @param code the value for app_version.code
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.lowest_code
     *
     * @return the value of app_version.lowest_code
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public String getLowestCode() {
        return lowestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.lowest_code
     *
     * @param lowestCode the value for app_version.lowest_code
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setLowestCode(String lowestCode) {
        this.lowestCode = lowestCode == null ? null : lowestCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.version
     *
     * @return the value of app_version.version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.version
     *
     * @param version the value for app_version.version
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.update_url
     *
     * @return the value of app_version.update_url
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public String getUpdateUrl() {
        return updateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.update_url
     *
     * @param updateUrl the value for app_version.update_url
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setUpdateUrl(String updateUrl) {
        this.updateUrl = updateUrl == null ? null : updateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.describe
     *
     * @return the value of app_version.describe
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.describe
     *
     * @param describe the value for app_version.describe
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.create_time
     *
     * @return the value of app_version.create_time
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.create_time
     *
     * @param createTime the value for app_version.create_time
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.creater
     *
     * @return the value of app_version.creater
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.creater
     *
     * @param creater the value for app_version.creater
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_version.is_exist
     *
     * @return the value of app_version.is_exist
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public Integer getIsExist() {
        return isExist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_version.is_exist
     *
     * @param isExist the value for app_version.is_exist
     *
     * @mbggenerated Mon Jun 06 17:19:50 CST 2016
     */
    public void setIsExist(Integer isExist) {
        this.isExist = isExist;
    }
}