package com.jianfei.core.bean;

import java.io.Serializable;

public class YdycAirports implements Serializable {
    private static final long serialVersionUID = 7171806678532830665L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ydyc_airports.id
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ydyc_airports.city
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ydyc_airports.airport_name
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    private String airportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ydyc_airports.airport_id
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    private String airportId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ydyc_airports.id
     *
     * @return the value of ydyc_airports.id
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ydyc_airports.id
     *
     * @param id the value for ydyc_airports.id
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ydyc_airports.city
     *
     * @return the value of ydyc_airports.city
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ydyc_airports.city
     *
     * @param city the value for ydyc_airports.city
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ydyc_airports.airport_name
     *
     * @return the value of ydyc_airports.airport_name
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public String getAirportName() {
        return airportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ydyc_airports.airport_name
     *
     * @param airportName the value for ydyc_airports.airport_name
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public void setAirportName(String airportName) {
        this.airportName = airportName == null ? null : airportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ydyc_airports.airport_id
     *
     * @return the value of ydyc_airports.airport_id
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public String getAirportId() {
        return airportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ydyc_airports.airport_id
     *
     * @param airportId the value for ydyc_airports.airport_id
     *
     * @mbggenerated Tue Jul 12 15:09:28 CST 2016
     */
    public void setAirportId(String airportId) {
        this.airportId = airportId == null ? null : airportId.trim();
    }
}