package com.jianfei.core.service.base;

import com.jianfei.core.bean.AppConfig;

import java.util.List;

/**
 * APP Config manager
 *
 * @version 1.0.0
 * @Description:
 * @author: liu.dongsong@jianfeitech.com
 * @date: 2016/5/31 10:19
 */
public interface AppConfigManager {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    AppConfig selectByPrimaryKey(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config
     *
     * @mbggenerated Tue May 31 10:16:16 CST 2016
     */
    List<AppConfig> selectByType(String id);
}
